defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "default"
    permalink: /:basename
plugins:
  - jekyll-seo-tag
title: 956 Productions
tagline: "Vortex Gallery: Winter Gaiden"
description: "VORTEX GALLERY returns to bring you 3 weekends of blockbuster fighting action in GUILTY GEAR -STRIVE-, MELTY BLOOD: TYPE LUMINA and THE KING OF FIGHTERS XV."
smashgg: https://smash.gg/wintergaiden
twitch: https://twitch.tv/956productions
twitter: 
  username: 956productions
  card: summary
logo: /img/logo.png
youtube: https://956pro.com/youtube
nav:
  - title: FAQ
    url: /faq
  - title: Games
    url: /games
  - title: Player's Guide
    url: /guide
  - title: Schedule
    url: /schedule
  - title: Staff
    url: /staff